### ISSUE TITLE
Smooth transition between views

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_D#25]
### SCENARIO: 
  
  - Ensure transition from desktop to mobile view and vice versa is smooth
    
    ### GIVEN: 
    
    - I am a user accessing the recipe app
    
    ### WHEN: 
    
    - I resize my browser from desktop to mobile size or vice versa
    
    ### THEN: 
    
    - The display of recipe list should adapt smoothly to the new view without requiring a page refresh

**Comment by Renzo-codespace** [comment]
The solution to this issue must be demonstrated before it can be considered as done.

**Comment by KagisoRabeng** [comment]
![Screenshot 2023-11-09 115241](https://github.com/CodeSpace-Academy/ASE_2023_GROUP_D/assets/125879959/f16ce3f9-16e0-4e95-84d6-d45a6d90ecd3)

**Comment by Renzo-codespace** [comment]
@codespace-justin Could you please shed some light on this for me? Issue description vs. origin of the uncaught error.

**Comment by codespace-justin** [comment]
Thanks @KagisoRabeng . @Renzo-codespace to be honest i havent had a chance to have a look at this yet so im not 100% certain what or where the error is actually being thrown from. 

I'll take a dive into the app with @KagisoRabeng & @OlebogengKhunou to try and bring this issue to light.
