### ISSUE TITLE
Example Bug

### ISSUE THREAD

**Issue by codespace-justin** [CodeSpace-Academy/ASE_2023_GROUP_D#46]
More Details:
https://www.notion.so/Bug-Template-enter-bug-name-739911a11462425a92d7a766d051a6ff?pvs=4

**Comment by codespace-justin** [comment]
hi

**Comment by Renzo-codespace** [comment]
@codespace-justin Do you need this or can I delete it?

**Comment by codespace-justin** [comment]
@Renzo-codespace Hey Renzo, sorry for any confusion caused by this. It was just an example for the students but i will delete it for you now/

**Comment by Renzo-codespace** [comment]
@codespace-justin No problem, just checking, cleaning, housekeeping, rows, ducks, etc.
